import pygame
from pacman import Pacman
from food import PacGomme
from collision import Building
from ghost import Fantome
from score import Score
from vie import Vie
from map import Map

class Game:
    def __init__(self):
        pacman_spritesheet = pygame.image.load("Sprite/Sprite.png").convert()
        self.player = Pacman(7,7, pacman_spritesheet)

        # Création des colisions 
        self.wall_left = pygame.sprite.Group()
        self.wall_up = pygame.sprite.Group()
        self.wall_down = pygame.sprite.Group()
        self.wall_right = pygame.sprite.Group()

        self.wall_left.add(Building('Sprite/Colision-Map-gauche.png', 0, 0))
        self.wall_up.add(Building('Sprite/Colision-Map-haut.png', 0, 0))
        self.wall_down.add(Building('Sprite/Colision-Map-bas.png', 0, 0))
        self.wall_right.add(Building('Sprite/Colision-Map-droite.png', 0, 0))

        # Création des pac-gommes 
        self.pac_gommes = pygame.sprite.Group()
        self.pac_gommes.add(PacGomme(20, 20, 'Sprite/Pac-Gomme.png', 50, True))
        self.pac_gommes.add(PacGomme(415, 20, 'Sprite/Pac-Gomme.png', 50, True))
        self.pac_gommes.add(PacGomme(20, 465, 'Sprite/Pac-Gomme.png', 50, True))
        self.pac_gommes.add(PacGomme(415, 465, 'Sprite/Pac-Gomme.png', 50, True))
        self.pac_gommes.add(PacGomme(55, 25, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(80, 25, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(102, 25, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(125, 25, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(150, 25, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(175, 25, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(198, 25, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(198, 55, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(102, 55, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(198, 85, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(25, 85, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(25, 55, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(55, 85, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(80, 85, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(102, 85, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(125, 85, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(150, 85, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(175, 85, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(220, 85, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(245, 85, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(270, 85, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(295, 85, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(320, 85, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(342, 85, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(365, 85, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(390, 85, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(420, 85, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(245, 25, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(270, 25, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(295, 25, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(320, 25, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(342, 25, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(365, 25, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(390, 25, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(245, 55, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(342, 55, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(420, 55, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(25, 135, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(55, 135, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(80, 135, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(102, 135, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(150, 135, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(175, 135, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(198, 135, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(245, 135, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(270, 135, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(295, 135, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(342, 135, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(365, 135, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(390, 135, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(420, 135, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(25, 110, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(102, 110, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(150, 110, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(295, 110, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(342, 110, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(420, 110, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(102, 160, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(342, 160, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(198, 160, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(245, 160, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(102, 183, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(342, 183, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(102, 207, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(342, 207, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(102, 230, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(342, 230, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(102, 257, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(342, 257, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(102, 282, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(342, 282, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(102, 305, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(342, 305, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(102, 325, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(342, 325, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(25, 325, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(55, 325, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(80, 325, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(102, 325, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(125, 325, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(150, 325, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(175, 325, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(198, 325, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(245, 325, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(270, 325, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(295, 325, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(320, 325, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(342, 325, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(365, 325, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(390, 325, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(420, 325, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(245, 350, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(342, 350, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(420, 350, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(198, 350, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(102, 350, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(25, 350, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(102, 375, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(342, 375, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(25, 375, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(55, 375, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(102, 375, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(125, 375, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(150, 375, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(175, 375, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(198, 375, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(245, 375, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(270, 375, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(295, 375, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(320, 375, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(342, 375, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(390, 375, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(420, 375, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(55, 400, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(102, 400, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(150, 400, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(295, 400, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(342, 400, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(390, 400, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(25, 425, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(55, 425, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(80, 425, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(102, 425, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(150, 425, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(175, 425, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(198, 425, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(245, 425, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(270, 425, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(295, 425, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(342, 425, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(365, 425, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(390, 425, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(420, 425, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(245, 450, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(420, 450, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(198, 450, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(25, 450, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(198, 470, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(55, 470, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(80, 470, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(102, 470, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(125, 470, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(150, 470, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(175, 470, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(220, 470, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(245, 470, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(270, 470, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(295, 470, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(320, 470, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(342, 470, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(365, 470, 'Sprite/Point.png', 10, False))
        self.pac_gommes.add(PacGomme(390, 470, 'Sprite/Point.png', 10, False))
        
        # Création des fantômes
        self.fantomes = pygame.sprite.Group()
        self.blinky = Fantome(50, 45, 'Sprite/Fantome.png', Map().get_map())    
        self.pinky = Fantome(10, 10, 'Sprite/Fantome.png', Map().get_map())
        self.inky = Fantome(20, 20, 'Sprite/Fantome.png', Map().get_map())
        self.clyde = Fantome(25, 25, 'Sprite/Fantome.png', Map().get_map())

        self.fantomes.add(self.blinky,self.pinky, self.inky, self.clyde)
        
        # Définition des fantômes principaux
        self.blinky = self.fantomes.sprites()[0]
        self.pinky = self.fantomes.sprites()[1]
        self.inky = self.fantomes.sprites()[2]
        self.clyde = self.fantomes.sprites()[3]
